version: '3.1'

services:
  database:
    container_name: db-container
    image: postgis/postgis:15-3.3
    restart: always
    hostname: docker-db
    environment: { "POSTGRES_PASSWORD": "example", "POSTGRES_USER": "postgres", "TZ": "utc" }
    volumes: [ "./20-create-role.sql:/docker-entrypoint-initdb.d/20-create-role.sql" ]
    ports: [ "25432:5432" ]
    networks: [ "pgnet" ]
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    depends_on: [ "database" ]
    restart: always
    hostname: docker-pgadmin
    environment: { "PGADMIN_DEFAULT_EMAIL": "example@example.com", "PGADMIN_LISTEN_PORT": "8080", "PGADMIN_DEFAULT_PASSWORD": "pgadminpass" }
    ports: [ "8080:8080" ]
    networks: [ "pgnet" ]
networks:
  pgnet:
    name: postgis-net
