services:
  database:
    container_name: postgis
    image: postgis/postgis:latest
    restart: always
    hostname: docker-postgis
    environment: { "POSTGRES_PASSWORD": "example", "POSTGRES_USER": "postgres", "TZ": "utc" }
    volumes: [ "./20-create-role.sql:/docker-entrypoint-initdb.d/20-create-role.sql:ro", "./psqlrc:/etc/postgresql-common/psqlrc:ro" ]
    ports: [ "25432:5432" ]
    networks: { "pgnet" : { "aliases": [ "db" ] } }
  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    depends_on: [ "database" ]
    restart: always
    hostname: docker-pgadmin
    environment: { "PGADMIN_DEFAULT_EMAIL": "example@example.com", "PGADMIN_LISTEN_PORT": "8080", "PGADMIN_DEFAULT_PASSWORD": "pgadminpass" }
    ports: [ "8080:8080" ]
    networks: { "pgnet" : { "aliases" : [ "pgadmin" ] } }
networks:
  pgnet:
    name: postgis-net
    ipam: { "driver": "default", "config": [ { "subnet": "10.0.1.0/24" } ] }
