name: geospatial-python
on: 
  push:
    branhces:
      - main
    paths:
      - python_geospatial/**
      - scipy_python/**
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: default-make-rule
        run: cd python_geospatial && make


