name: fsharp-with-r
on: 
  workflow_dispatch:
  push: { "branches": [ "main" ], "paths": [ "fsharp-with-R/**" ] }
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps: [ {"name": "Checkout repository", "uses": "actions/checkout@v3"}, 
             {"name": "Default make rule", "run": "cd datascience-docker && make"} ]
