name: lilypond
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lilypond/**
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Default make rule
        run: cd lilypond  && SILENT=1 make


