name: pandoc-with-komascript
on: 
  push: { "branches": [ "main" ], "paths": [ "pandoc-docker/**" ] }
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps: [ {"name": "Checkout repository", "uses": "actions/checkout@v3"}, 
             {"name": "Default make rule", "run": "cd pandoc-docker && make"} ]
