name: spark
on:
  push:
    branches:
      - main
    paths:
      - dockerize_spark/**
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Default make rule
        run: cd dockerize_spark && make


